### PR TITLE
Hoy En TV

### PR DESCRIPTION
**Pull request by MrTruth0**
Added "Hoy en tv" like in SOD.

Please, Check if the json, the item in channelselector and words are correct.

By iSOD Crew

### CODE REVIEW

**Comment by Intel11** [comment]
Hi, can you add the corresponding icon?
Because it does not look good, with the other icons.
Greetings.

image

**Comment by pipcat** [comment]
A parte del icono, no creo conveniente añadir esta opción al addon. Es más para un plugin tipo tvalacarta que para un pelisalacarta.

**Comment by MrTruth0** [comment]
@pipcat That was a required script ... i spent time on that, if you want i can remove the PR, but i will not make other scripts ... Understand me, I do not have much time ...

**Comment by mrgaturus** [comment]
@MrTruth0 so, PR this to tvalacarta, the script structure is closer to this

**Comment by MrTruth0** [comment]
Ok, I will close this, as I said, that was a REQUIRED script, but it's ok..

**Pull request closed without merging**
