### PR TITLE
fix opción hd

### PR DESCRIPTION
**Pull request by DamianBacalov**
I've created 2 decrypt and one recursive functions.

### CODE REVIEW

**Comment by alfa-addon** [comment]
Error in Kodi 19.  It's mandatory to verify every module against Kodi 19 to be accepted.  Please, fix asap and resubmit:

Files\Kodi_19\Kodi\portable_data\addons\plugin.video.alfa\channels\estrenosdoramas.py", line 312, in findvideos
                                                       for option, scrapedurl in map(None, option_matches, video_matches):
                                                   TypeError: 'NoneType' object is not callable

**Comment by alfa-addon** [comment]
Have you REALLY tested it against Kodi 19?  Update Alfa and you'll see the changes I've done in lines 352, 380.  Please, fix your PR accordingly.

**Comment by alfa-addon** [comment]
_"_Have you REALLY tested it against Kodi 19? Update Alfa and you'll see the changes I've done in lines 347, 352, 375, 380. Please, fix your PR accordingly._"_

When I first sent this comment, there were two lines to fix, but then I edited because really they were 4 lines.  I wonder if you saw only the original message.  Please change the 4 lines, otherwise it'll not work in Kodi 19.

**Comment by DamianBacalov** [comment]
I've tested it with kodi 19 and it works fine now

**Pull request merged**
